### ISSUE TITLE
dev: Trying to push a PR, but do not have access rights

### ISSUE THREAD

**Issue by mathDR** [JaxGaussianProcesses/MOGPJax#7]
Hello!  I am currently looking at this repo, and finding some issues in some of the files.  As I think I would like to utilize a lot of this functionality, I am "fixing" things as I find them.

I currently have a PR ready to go that fixes the `gplvm.pct.py` example, but cannot push it for code review, as I do not have access rights.

perhaps you can grant me a temporary token so I can push this (and other) PRs?

**Comment by Daniel-Dodd** [comment]
Hi @mathDR, Thanks for spotting #6 and your interest in contributing.

For new contributors, our preferred route to contribute to any library in the `JaxGaussianProcesses` ecosystem (designed to avoid access right issues) is to (1) fork the repository, (2) push your changes to your fork, (3) open a PR from your fork. We still need to write these steps in an official contribution guide for `MOGPJax` (and for a few of our other libraries - this is near the top of our to-do list)! But the guide for `GPJax`, which outlines the same steps, can be found [here](https://gpjax.readthedocs.io/en/latest/contributing.html).

I look forward to reviewing your PR! Please let me know if you have any further questions. :)
